In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [3]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

### Q1. Pandas version
What's the version of Pandas that you installed?

In [4]:
 pd.__version__

'2.3.1'

### Q2. Records count
How many records are in the dataset?

In [5]:
df.shape

(2160, 12)

### Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [6]:
df['Brand'].nunique()

27

In [7]:
df['Brand'].value_counts()

Brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Deep Gaming           8
Primux                8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

### Q4. Missing values

How many columns in the dataset have missing values?

In [8]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [9]:
cols = df.columns
null_count = []


for i in cols:
    if df[i].isnull().sum()>0:
        null_count.append(1)
    n_null_col = sum(null_count)
        

print(f"The number of columns with missing values is {n_null_col}")

The number of columns with missing values is 3


### Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

In [10]:
df[df['Brand']=='Dell']['Final Price'].max().round()

np.float64(3936.0)

In [11]:
df.groupby('Brand')['Final Price'].max().round()

Brand
Acer                3691.0
Alurin               869.0
Apple               3849.0
Asus                5758.0
Deep Gaming         1639.0
Dell                3936.0
Denver               330.0
Dynabook Toshiba    1805.0
Gigabyte            3799.0
HP                  5369.0
Innjoo               431.0
Jetwing              469.0
LG                  2399.0
Lenovo              5018.0
MSI                 7150.0
Medion              3799.0
Microsoft           3748.0
Millenium           2313.0
PcCom               1950.0
Primux               599.0
Prixton              330.0
Razer               4999.0
Realme               999.0
Samsung             3699.0
Thomson              437.0
Toshiba              799.0
Vant                1217.0
Name: Final Price, dtype: float64

### Q6. Median value of Screen

1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.

Has it changed?

<b>Hint:</b> refer to existing mode and median functions to complete the task

In [12]:
# 1. Find the median value of Screen column in the dataset.
df['Screen'].median()

np.float64(15.6)

In [13]:
# 2. Next, calculate the most frequent value of the same Screen column.
df['Screen'].value_counts()

Screen
15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.40      19
13.50      19
11.60      16
14.20      14
12.30      13
14.10      11
13.60      11
16.20      10
15.30       8
10.50       7
12.40       6
14.40       6
15.40       5
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.95       1
10.10       1
Name: count, dtype: int64

In [14]:
df['Screen'].value_counts().max()

np.int64(1009)

In [15]:
# 3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

#checking the missing values
df['Screen'].isnull().sum()

np.int64(4)

In [16]:
max_count = df['Screen'].value_counts().max()

#fills all the missing values on the column Screen by the most frequent value
df['Screen'] = df['Screen'].fillna(max_count)

In [17]:
#check that the null values were replaced
df['Screen'].isnull().sum()

np.int64(0)

In [40]:
# 4. Now, calculate the median value of Screen once again.
df['Screen'].median()

np.float64(15.6)

### The median value is the same after replacing the null values

### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?

In [19]:
# 1. Select all the "Innjoo" laptops from the dataset.
df[df['Brand']=='Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [20]:
# 2. Select only columns RAM, Storage, Screen.
df[df['Brand']=='Innjoo'][['RAM','Storage','Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [21]:
# 3. Get the underlying NumPy array. Let's call it X.
X = df[df['Brand']=='Innjoo'][['RAM','Storage','Screen']].values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [31]:
X.shape

(6, 3)

In [22]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XT =X.T
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [32]:
XT.shape

(3, 6)

In [23]:
XTX = XT.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [33]:
XTX.shape

(3, 3)

In [24]:
# 5. Compute the inverse of XTX.
I_XTX = np.linalg.inv(XTX)
I_XTX


array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [34]:
I_XTX.shape

(3, 3)

In [25]:
# 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [35]:
# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
I_XTX_multip_XT_multip_y = I_XTX.dot(XT).dot(y)



In [36]:
I_XTX_multip_XT

array([45.58076606,  0.42783519, 45.29127938])

In [39]:
print(f"The sum of all the elements of the result is {sum(I_XTX_multip_XT).round()}")

The sum of all the elements of the result is 91.0
